Add missing 'apt update' when adding a file to /etc/apt/sources.list.d/'

diff --git a/autoinstall b/autoinstall
--- a/autoinstall
+++ b/autoinstall
@@ -212,6 +212,13 @@ add_deb_source() {
     echo "$string" > "$filename"
     echo "Added package source in $filename"
   fi
+
+  echo "Added repository: $repo, running 'apt update'"
+  apt update >& /dev/null
+  if [[ $? -ne 0 ]]; then
+    echo "Error updating package list. Exiting."
+    bail 1
+  fi
 }
 
 # Add a repository using add-apt-repository
